### ISSUE TITLE
Nested references raises unhandled exception

### ISSUE THREAD

**Issue by stzr1123** [deliveryhero/dh-disco-flask-swagdeco#1]
Consider the following schema structure.
schema1.yml
```
definitions:
  thing_1:
      type: object
      required:
        - property_1
      additionalProperties: false
      properties:
        property_1:
          $ref: 'common#/definitions/property_1'
```
common.yml
```
definitions:
  property_1:
    $ref: '#/definitions/base_property'

  base_property:
    type: object
    required:
      - name
    additionalProperties: false
    properties:
      name:
        $ref: '#/definitions/some_other_definition'
```

When this schema is used to validate a json file, the nested reference traversal fails. Validation is called by `dh-disco-flask-swagdeco/flask_swagdeco/swagger.py", line 62, in validate_request_schema`.

The produced schema contains an object of type `_WrappedValue` instead of the proper nested structure.

Find attached a traceback.

[test_out_11.txt](https://github.com/deliveryhero/dh-disco-flask-swagdeco/files/1471269/test_out_11.txt)
